#pragma config(Motor,  port1,           driveright,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          driveright,    tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// BEFORE PROGRAMMING YOU MUST READ THE INSTRUCTIONS!!!


//--------------------------------------------------------------------------------------------

//STEP ONE

   // BEFORE YOU BEGIN PROGRAMMING, YOU MUST INPUT YOUR SETTINGS. GO TO THE TAB "Robot" IN THE UPPER LEFT CORNER OF THE SCREEN, AND CLICK "Platform Type"
	// AFTER YOU CLICK "Platform Type" SELECT "VEX 2.0 CORTEX." ONCE YOU HAVE SELECTED 2.0 CORTEX, GO BACK AND ALSO SELECT "NATURAL LANGUAGE 2.0" AS YOUR
	// PROGRAMMING LANGUAGE. YOU MUST HAVE A BULLETPOINT OR CHECKMARK IN BOTH BOXES TO PROCEDED.


	//PLATFORM TYPE: VEX 2.0 CORTEX ------ PROGRAM WILL NOT WORK ELSEWISE


	//PROGRAMMING LANGUAGE: NATURAL LANGUAGE 2.0


//---------------------------------------------------------------------------------------------------------------------------

//STEP TWO

	// SET THE CORTEX COMMUNICATION MODE: VEXNET OR USB   IN ORFER TO CHANGE THIS SETTING, CLICK THE LABEL "Robot" IN THE UPPER LEFT CORNER OF THE SCREEN,
	// THEN CLICK "Vex Cortex Communication Mode" AND SET IT TO "VexNet Or USB"
	// COMMUNICATION MODE MUST BE SET TO VEXNET OR USB OR YOU WILL NOT BE ABLE TO USE YOUR REMOTE!


//--------------------------------------------------------------------------------------------------------------------------------------

// STEP THREE

	// MAKE SURE TO UPDATE FIRMWARE ON ROBOT CORTEX BEFORE DOWNLOADING ANY PROGRAM FOR THE FIRST TIME
	// TO DOWNLOAD FIRMWARE YOU MUST CONNECT YOUR ROBOT'S CORTEX TO THE COMPUTER AND CLICK THE "Firmware Download" BUTTON.

//--------------------------------------------------------------------------------------------------------------------------------------

//STEP FOUR

	//COPY THE COLORED PROGRAM INTO YOUR PROGRAM EXACTLY AS YOU SEE IT. THIS INCLUDES THE #PRAGMA INCLUDES, UNLESS YOU ALREADY HAVE SET UP YOUR MOTORS
	//THROUGHT THE "Motor and Sensor Setup" PAGE.

//DO NOT INCLUDE ANY TEXT IN GREEN IN YOUR PROGRAM. ALL INSTRUCTIONS ARE FOR DEMONSTRATION USE ONLY AND ARE NOT NEEDED TO MAKE YOUR ROBOT FUNCTION.

#pragma config(Motor,  port1,           driveright,    tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          driveright,    tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while(true)  //SET INFINITE LOOP FOR CONSTANT REMOTE CONTROL
	{
		motor(port1) = vexRT(Ch2);         // SET MOTOR WITH COMMAND motor(motorport) and assign vex joystick axis by adding
                                       // = vexRT(JoystickAxis) in format (ChCHANNEL) and add semicolon
		motor(port10) = vexRT(Ch3);        // REPEAT FOR THE SECOND AXIS
	}


//-----------------------------------------------------------------------------------------------------------------------------------------------------

//STEP FIVE

	//YOU MUST NOW SAVE AND DOWNLOAD YOUR PROGRAM TO YOUR ROBOT. CLICK THE SAVE BUTTON AND SAVE YOUR PROGRAM TO A FLASHDRIVE OR TO YOUR Z-DRIVE.
	//AFTER SAVING YOUR PROGRAM, CONNECT YOUR CORTEX TO THE COMPUTER IF YOU HAVE NOT ALREADY DONE SO AND THEN CLICK THE "Download to Robot BUTTON.


//-------------------------------------------------------------------------------------------------------------------------------------------------------

// INSTRUCTIONS BY ANDREW HENKE


//----------------------------------------------------------------------------------------------------------------------------------------------------


}
