#pragma config(Motor,  port2,           liftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true)
{

motor(port3) = vexRT(Ch2);
motor(port4) = vexRT(Ch3);

if(vexRT(Btn6U)==1)
{
	setMotor(port2,100);
}

	if(vexRT(Btn6D)==1)
{
		setMotor(port2,-100);


}

}

}
