#pragma config(Motor,  port2,           motorLeft,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           motorRight,    tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while(true)


 {
   motor(port2) = vexRT(Ch3);
   motor(port3) = vexRT(Ch2);
 }
//Programmed by Andrew 6-3-19 (Week One)

}
